const exampleData = [
  {
    id: 218,
    bus_id: 10,
    user_id: 76,
    description: 'Soluta magnam laudantium omnis eos dolorem.',
    link: 'https://s3-us-west-1.amazonaws.com/yelpest/pic7.jpg',
    date: '2018-07-03T07:00:00.000Z',
    helpful: 3,
    not_helpful: 1,
    user_name: 'Carlotta B.',
    is_owner: 1,
    friends: 2410,
    reviews: 1052,
    elite_status: 1,
    bus_name: 'Chenoy\'s Delicatessen',
    takes_reservation: 0,
  },
  {
    id: 241,
    bus_id: 10,
    user_id: 113,
    description: 'Ipsum earum nihil aspernatur.',
    link: 'https://s3-us-west-1.amazonaws.com/yelpest/pic3.jpg',
    date: '2017-09-15T07:00:00.000Z',
    helpful: 3,
    not_helpful: 0,
    user_name: 'Andres S.',
    is_owner: 1,
    friends: 1869,
    reviews: 1988,
    elite_status: 0,
    bus_name: 'Chenoy\'s Delicatessen',
    takes_reservation: 0,
  },
  {
    id: 242,
    bus_id: 10,
    user_id: 122,
    description: 'Voluptas voluptatem in voluptatum ut consequatur sit quia.',
    link: 'https://s3-us-west-1.amazonaws.com/yelpest/pic2.jpg',
    date: '2018-07-19T07:00:00.000Z',
    helpful: 9,
    not_helpful: 2,
    user_name: 'Eva M.',
    is_owner: 1,
    friends: 2332,
    reviews: 71,
    elite_status: 0,
    bus_name: 'Chenoy\'s Delicatessen',
    takes_reservation: 0,
  },
  {
    id: 406,
    bus_id: 10,
    user_id: 68,
    description: 'Et dolorem ipsam voluptas corrupti.',
    link: 'https://s3-us-west-1.amazonaws.com/yelpest/pic8.jpg',
    date: '2018-05-04T07:00:00.000Z',
    helpful: 0,
    not_helpful: 5,
    user_name: 'Ezekiel R.',
    is_owner: 1,
    friends: 2237,
    reviews: 278,
    elite_status: 0,
    bus_name: 'Chenoy\'s Delicatessen',
    takes_reservation: 0,
  },
  {
    id: 704,
    bus_id: 10,
    user_id: 9,
    description: 'Cum consectetur vero ea veniam sit maxime minus laboriosam.',
    link: 'https://s3-us-west-1.amazonaws.com/yelpest/pic6.jpg',
    date: '2017-09-13T07:00:00.000Z',
    helpful: 10,
    not_helpful: 0,
    user_name: 'Kian G.',
    is_owner: 1,
    friends: 2479,
    reviews: 1263,
    elite_status: 0,
    bus_name: 'Chenoy\'s Delicatessen',
    takes_reservation: 0,
  },
  {
    id: 799,
    bus_id: 10,
    user_id: 120,
    description: 'Error omnis et aut fugiat ut cum enim sed cumque.',
    link: 'https://s3-us-west-1.amazonaws.com/yelpest/pic6.jpg',
    date: '2018-05-13T07:00:00.000Z',
    helpful: 4,
    not_helpful: 3,
    user_name: 'Leopold L.',
    is_owner: 1,
    friends: 2720,
    reviews: 2534,
    elite_status: 0,
    bus_name: 'Chenoy\'s Delicatessen',
    takes_reservation: 0,
  },
  {
    id: 867,
    bus_id: 10,
    user_id: 243,
    description: 'Est aliquam qui dolorum aspernatur quibusdam eos labore.',
    link: 'https://s3-us-west-1.amazonaws.com/yelpest/pic9.jpg',
    date: '2018-05-31T07:00:00.000Z',
    helpful: 8,
    not_helpful: 4,
    user_name: 'Russel B.',
    is_owner: 0,
    friends: 2948,
    reviews: 328,
    elite_status: 0,
    bus_name: 'Chenoy\'s Delicatessen',
    takes_reservation: 0,
  },
];

module.exports = exampleData;
